### ISSUE TITLE
CPU Temp/RTC Temp

### ISSUE THREAD

**Issue by jopeg** [embeddedTS/ts7670-utils-linux4.x#3]
Regarding the TS7670, I have noticed that the two temperatures provided by previous tshwctl releases are not available in tshwctl or tsmicroctl. I am referring to the temps returned by these two commands: 
* tshwctl --rtcinfo
* tshwctl --cputemp

I have checked and the kernel doesn't have any temperature sensors setup. Perhaps this is due to the device tree not having support for it?

**Comment by ts-kris** [comment]
Thanks for bringing this to our attention. I'll dig in a little bit more. The idea was indeed to have the kernel be able to report that information but it is possible that the FDT was not set up correctly for this.

**Comment by jopeg** [comment]
Thanks for the fast response, look forward to hearing your findings. 
Let me know if I can help or get you more info.

**Comment by ts-kris** [comment]
Sorry it took so long to look in to this.

See commit 72fa03ac0e592141613136ea4584bfe984f11617

I've added this feature back in, but it must be enabled at compile time with a define. Since temperature sensing requires temperature compensation to be enabled, I'm not sure of any side effects that may arise.


As for reading the CPU temperature, again the ADC has been hooked up in the kernel rather than the userspace utility. And so as not to risk stepping on the kernel, `tshwctl` doesn't have that ability. However, the 4.9 kernel driver can read the die temperature:

```
TEMP_RAW=`cat /sys/bus/iio/devices/iio:device0/in_temp8_raw`
TEMP_OFFSET=`cat /sys/bus/iio/devices/iio:device0/in_temp8_offset | sed 's/-/_/'`
TEMP_SCALE=`cat /sys/bus/iio/devices/iio:device0/in_temp8_scale`

TEMP=`echo "${TEMP_RAW} ${TEMP_OFFSET} + ${TEMP_SCALE} * p" | dc`
echo ${TEMP}
```

Make sure you install `dc` ahead of time. You can also integrate this in to your own application or script as needed.

Unfortunately, the driver does not expose the temperature in any Linux normalized way (usually through `/sys/class/thermal/...`) but the above commands can at least get the correct die temperature.
